version: "3"
services:
  dev:
    container_name: 2bg.gg
    build:
      context: .
      dockerfile: Dockerfile
    env_file: .env
    user: "${UID}:${GID}"
    ports:
      - "8080"
      - "8787"
    volumes:
      - ./:/workspace
      - 2bg-web-node_modules:/workspace/app/node_modules
      - 2bg-api-node_modules:/workspace/api/node_modules
    command: sleep infinity

volumes:
  2bg-web-node_modules:
  2bg-api-node_modules:
