name: Deploy

concurrency: production
cancel-in-progress: true

on:
  push:
    branches:
      - main

jobs:
  deploy:
    steps:
      uses: cloudflare/wrangler-action@1.3.0
      with:
        apiToken: ${{ secrets.CF_API_TOKEN }}
        environment: 'production'